# ====================== 基础配置 ======================
name: "msssim119"
epochs: 80
batch_size: 8
device: "cuda"
# pretrained: "log_mxz/msssim105_10_10_19_11_34/models/model_last.pt"
pretrained: ""  # 无预训练模型时取消注释

# ====================== 损失函数权重 ======================
alpha0: 1.0    # 井曲线阻抗损失权重
alpha1: 0.5    # 重建损失权重
alpha2: 0.0   # 频谱损失权重
# alpha2: 0.05   # 频谱损失权重


# ====================== 重建损失配置 ======================
recons_type: "msssim"  # 可选: mse, cross, msssim
rickerf: 45            # ricker子波频率

# ====================== 数据路径配置 ======================
root_dir: "../out/seis/train/"
train_split: "trainimp"
valid_split: "validimp"
test_seis_path: "../out/seis/train/validimp/sx/125-833.dat"
test_imp_path: "../out/seis/train/validimp/ws/125-833.dat"
test_log_path: "../out/seis/train/validimp/wx/125-833.dat"
ref_spectrum_path: "ref_spec.npy"  # 频谱参考文件

# ====================== 数据维度配置 ======================
h_dim: 251               # 时间维度/深度维度大小


# ====================== 训练日志配置 ======================
log_root: "log_cnooc"       # 日志/模型保存根目录
save_model_interval: 10   # 模型保存间隔（epoch）
log_image_dpi: 300        # 日志图片DPI
